---
title: "cool title"
date: 2023-02-13T11:30:19+01:00
draft: false
---
[.bigtype]
== #Überneu# is a #playground# for exciting ideas and potential ventures.  

Everyday life and thought experiments inspire our work. + 
We believe that Überneues (German: the overly, all too new) arise from structured processes in combination with creative openness.

Although it is curiosity and the joy of encountering new things, ideas, and concepts that drive us, projects we take on must also have a positive effect and a solid economic basis. The results are tangible products, cultural interventions, or digital artifacts.

== Our projects
{{< project-teaser count="4" >}}

== Office hours
New ideas derive from conversations—and while we do not actively search for clients, we always love to meet people. Together we create something new by merging ideas, skills, and goals. +
Please feel free to reach out via mailto:hi@ueberneu.de[email].

Or directly grab a slot in our calendar—no strings attached. +
-> https://cal.com/ueberneu[#Book a slot#]
